import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import AuthActions from '../components/AuthActions';
import Clock from '../components/Clock';
import ExpBar from '../components/ExpBar';
import MemberList from '../components/MemberList';
import MessageForm from '../components/MessageForm';
import Modal from '../components/Modal';
import OnlineStatus from '../components/OnlineStatus';
import RoomEditor from '../components/RoomEditor';
import Timeline from '../components/Timeline';
import YouTubeControler from '../components/YouTubeControler';
import YouTubePlayer from '../components/YouTubePlayer';
import { classNames } from '../utils/classNames';

const Home: NextPage = () => {
  const [target, setTarget] = useState<any>();
  const [isChatOpen, setIsChatOpen] = useState<any>(true);
  const [playerState, setPlayerState] = useState<number>();
  const [isRoomOpen, setIsRoomOpen] = useState<boolean>(false);

  const initTarget = (event: any) => {
    setTarget(event.target);
  };

  const onStateChange = ({ data }: { data: number }) => {
    setPlayerState(data);
  };

  const toggleIsChatOpen = () => {
    setIsChatOpen((status: boolean) => !status);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative font-dot">
        <YouTubePlayer onReady={initTarget} onStateChange={onStateChange} />
        <div className="flex flex-col fixed inset-0 z-10">
          <header className="py-4 px-6 bg-black text-white flex items-center space-x-6">
            <h1>
              Webエンジニア系フリーランスのもくもく部屋 Lv.1{' '}
              <span title="非公開">🔒</span>
            </h1>
            <span className="flex-1"></span>
            <button
              onClick={() => setIsRoomOpen(true)}
              className="emoji"
              title="部屋を作る"
            >
              🔮
            </button>
            <button className="emoji" title="他の部屋を探す">
              🔍
            </button>
            <button title="ブロッコリー">
              <span className="emoji mr-1">🥦</span>
              <span>40</span>
            </button>
            <OnlineStatus />
            <button
              title={`チャットを${isChatOpen ? '非表示' : '表示'}`}
              className={classNames('emoji', !isChatOpen && 'opacity-40')}
              onClick={toggleIsChatOpen}
            >
              💬
            </button>
            <AuthActions />
            <Clock />
          </header>

          <main className="flex-1 grid grid-cols-3 overflow-hidden">
            <div className="py-4 px-6 col-span-2">
              <MemberList />
            </div>
            <div
              className={classNames(
                'col-span-1 p-4 h-full overflow-hidden',
                !isChatOpen && 'hidden'
              )}
            >
              <div className="rounded-md bg-black bg-opacity-30 p-6 text-white flex flex-col h-full">
                <MessageForm />
                <Timeline />
              </div>
            </div>
          </main>

          <footer className="flex px-6 items-center bg-black z-10 text-white justify-between">
            <YouTubeControler playerState={playerState} target={target} />
            <ExpBar />
          </footer>

          <Modal
            title="部屋を作る"
            isOpen={isRoomOpen}
            onClose={() => setIsRoomOpen(false)}
          >
            <RoomEditor />
          </Modal>
        </div>
      </main>
    </div>
  );
};

export default Home;
