import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import AuthActions from '../components/AuthActions';
import Clock from '../components/Clock';
import Gifs from '../components/Gifs';
import Image from 'next/image';
import MessageForm from '../components/MessageForm';
import OnlineStatus from '../components/OnlineStatus';
import Timeline from '../components/Timeline';
import YouTubePlayer from '../components/YouTubePlayer';
import { useAuth } from '../providers/AuthProvider';

const Home: NextPage = () => {
  const [target, setTarget] = useState<any>();
  const [playerState, setPlayerState] = useState<number>();
  const user = useAuth();

  const initTarget = (event: any) => {
    setTarget(event.target);
  };

  const play = () => {
    target?.playVideo();
  };

  const pause = () => {
    target?.pauseVideo();
  };

  const onStateChange = ({ data }: { data: number }) => {
    setPlayerState(data);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative font-dot">
        <YouTubePlayer onReady={initTarget} onStateChange={onStateChange} />
        <div className="flex flex-col fixed inset-0 z-10">
          <header className="py-4 px-6 bg-black text-white flex items-center space-x-6">
            <h1>Webエンジニア系フリーランスのもくもく部屋 Lv.1 🔒</h1>
            <span className="flex-1"></span>
            <button className="emoji">🔎</button>
            <OnlineStatus />
            <Clock />
            <AuthActions />
          </header>

          <main className="flex-1 grid grid-cols-3 overflow-hidden">
            <div className="m-10 p-10 bg-white relative col-span-2 opacity-0">
              {/* <Gifs /> */}
            </div>
            <div className="col-span-1 p-4 h-full overflow-hidden">
              <div className="rounded-md bg-black bg-opacity-30 p-6 text-white flex flex-col h-full">
                <MessageForm />
                <Timeline />
              </div>
            </div>
          </main>

          <footer className="flex justify-between bg-black z-10 text-white text-2xl">
            {playerState !== 1 && (
              <button className="flex p-4 emoji" onClick={play}>
                {/* <Image width="12" height="22" src="/images/play.svg" alt="" /> */}
                ▶︎
              </button>
            )}
            {playerState === 1 && (
              <button className="flex p-4 emoji" onClick={pause}>
                {/* <Image width="17" height="22" src="/images/pause.svg" alt="" /> */}
                ⏸
              </button>
            )}
          </footer>
        </div>
      </main>
    </div>
  );
};

export default Home;
